### ISSUE TITLE
Rename Bundle

### ISSUE THREAD

**Issue by harrisonbc** [gilphilbert/pqt2#21]
If you are adding multiple sdd files with bundles with the same name in it doesn't allow it. Can we have a rename option to allow this (either automatic or manual input)

**Comment by gilphilbert** [comment]
Are you adding the same bundle twice, or are these different bundles? Each bundle has a unique ID and PQT won't allow you to append a bundle if the ID already exists (this is when you'll see the error message. The name isn't a problem - it's this ID.

If you have two separate configs with two different bundles that you can't import, can you send them to me so I can look at them and work out why they're showing this behavior?

**Comment by harrisonbc** [comment]
I think you are right - I thought I was adding different versions of the same config but seems to work as expected.

**Comment by gilphilbert** [comment]
Cool. I'm going to close this, but reopen it if it comes up again

**Comment by harrisonbc** [comment]
I've spotted this one again with the attached files (different configs from a base build)



[JISC RFI RDSS - Hedvig - 3YrPC BCHV1_5110016698-01.zip](https://github.com/gilphilbert/pqt2/files/1138259/JISC.RFI.RDSS.-.Hedvig.-.3YrPC.BCHV1_5110016698-01.zip)

**Comment by gilphilbert** [comment]
OK, I get the use case for this.

Altered so now you can add two identical bundles to the same config (for comparison). Fix in https://github.com/gilphilbert/pqt2/commit/8e1bfb8e6763e4dffa8680438b11b228c8b94fc5
