### ISSUE TITLE
Enable CSV output of data

### ISSUE THREAD

**Issue by gilphilbert** [gilphilbert/pqt2#6]
Alongside PDF, allow CSV output (and potentially ASCII tables too)

**Comment by gilphilbert** [comment]
@harrisonbc - question:
CSVs are very simple... that leads to a few limitations
- We can't offer summary pages (not that make any sense)
- Since a CSV is a just a list of parts, each bundle in a config would need to be exported as a dedicated CSV file for the files to make any sense

Bearing those in mind, is CSV still a suitable file format?

**Comment by harrisonbc** [comment]
The use case for this is to enable extract of information from the BoM to other formats that the user can manipulate themselves in case there is a tweak needed. This can currently be done by selecting the text from the PDF and copying it into Notepad/EMails/Excel but was just looking to do this in a more elegant manner.
I see CSV (or even tab delimited) as an intermediary format that can be imported to something else so doesn't need any more processing in PQT2 just a BoM dump.

Thoughts?

**Comment by gilphilbert** [comment]
OK, so the use case for this is to simply dump a BOM?

That would be qty, sku, description without pricing?

If so, I can do that in a number of formats (CSV being the most likely) but you'd still want one per bundle, presumably. I assume you want something you can copy/paste from so PDF isn't suitable.

So what you're after is a BOM option that exports to CSV?

**Comment by gilphilbert** [comment]
https://github.com/gilphilbert/pqt2/commit/edabced6f63e6076e2be74635b119b6ccf6e3366
