### ISSUE TITLE
Prices not displayed on unticking Blended

### ISSUE THREAD

**Issue by harrisonbc** [gilphilbert/pqt2#8]
Low Priority Issue

On unticking "Blended" the pricing is not shown in Bundle Detail until one of the discount percentages is changed.
 
![image](https://user-images.githubusercontent.com/23299746/27859810-e384e2c6-6171-11e7-9e7e-65233af30ebb.png)
![image](https://user-images.githubusercontent.com/23299746/27859825-f20dd1b8-6171-11e7-9e75-cc7fe2ecedf0.png)

**Comment by gilphilbert** [comment]
Added in https://github.com/gilphilbert/pqt2/commit/a970470e5309a9b8ac5855c388f9ed48ab41fafd
