### ISSUE TITLE
Contact information is not shown if both Company & Contact Name are not included

### ISSUE THREAD

**Issue by harrisonbc** [gilphilbert/pqt2#9]
If I only include Company Name or Contact Name in the Quote Detail of the Export dialogue it is not included in the output

It would be nice if I could have the option of just including  one of them

**Comment by harrisonbc** [comment]
I've noticed that if I include a space then that works

**Comment by gilphilbert** [comment]
That's a good idea, so if you only fill in one of them, you'll only see that one (if information isn't included then it's not shown).

The "ValidTo" date is currently only shown if both Company Name and Contact Name are included (it defaults to 30 days). Should that always be included?

**Comment by harrisonbc** [comment]
I never use the valid to field, but id leave it there for those that do. Blank it out if not set by user




Get Outlook for Android







On Wed, Jul 5, 2017 at 6:59 PM +0100, "gilphilbert" <notifications@github.com> wrote:












Closed #9.
